### ISSUE TITLE
[Slack integration] Title missing from uploaded files

### ISSUE THREAD

**Issue by teka23** [looker-open-source/actions#516]
On files.completeUploadExternal, we are not passing file title, and it is showing up as Untitled.

https://github.com/looker-open-source/actions/blob/f9a87a9b67758271b9144770be6017992c61d30f/src/actions/slack/utils.ts#L140

https://github.com/looker-open-source/actions/blob/f9a87a9b67758271b9144770be6017992c61d30f/lib/actions/slack/utils.js#L111

**Comment by phillipperalez** [comment]
fixed recently
